CREATE TABLE [dbo].[TRC_ProductionTraceLot] (

	[lTraceLotPK] int NULL, 
	[dtTimestamp] datetime2(6) NULL, 
	[DefID] varchar(8000) NULL, 
	[szMaterialLotID] varchar(8000) NULL, 
	[szTrackingCode] varchar(8000) NULL, 
	[dQuantityBase] decimal(15,5) NULL, 
	[szEquipmentID] varchar(8000) NULL, 
	[szPomEntryID] varchar(8000) NULL, 
	[dtHistoryDate] datetime2(6) NULL, 
	[CreatedOn] datetime2(6) NULL, 
	[CreatedBy] varchar(8000) NULL, 
	[RowUpdated] datetime2(6) NULL, 
	[RowUpdatedBy] varchar(8000) NULL, 
	[szBinID] varchar(8000) NULL, 
	[szBaseUomID] varchar(8000) NULL, 
	[szPackingID] varchar(8000) NULL, 
	[dQuantityPacking] decimal(15,5) NULL, 
	[dPackingConvFactor] decimal(15,5) NULL, 
	[lProductionTypeID] varchar(8000) NULL, 
	[szSpare01] varchar(8000) NULL, 
	[szSpare02] varchar(8000) NULL, 
	[szSerialNumber] varchar(8000) NULL, 
	[szBatchID] varchar(8000) NULL
);